SELECT MAX(CUSTOMERS.NAME), MAX(MANAGERS.NAME)
FROM ORDERS 
	RIGHT JOIN CUSTOMERS ON CUSTOMER_ID = CUSTOMERS.ID
		LEFT JOIN MANAGERS ON MANAGER_ID = MANAGERS.ID 
WHERE DATE > '2013'
GROUP BY CUSTOMERS.ID
HAVING SUM(AMOUNT) > 10000 